# permissions for end users to view codereadyanalytics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codereadyanalytics-viewer-role
rules:
- apiGroups:
  - f8a.example.com
  resources:
  - codereadyanalytics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - f8a.example.com
  resources:
  - codereadyanalytics/status
  verbs:
  - get
