apiVersion: f8a.openshift.com/v1alpha1
kind: CodeReadyAnalytics
metadata:
  name: codereadyanalytics-sample
spec:
  config:
    common:
      authUrl: https://youareawesome.com
      deploymentPrefix: deepshar
      dynamodbPrefix: deepshar-dev
      threeScaleAccountSecret: abc
      awsDefaultRegion: us-east-1
      githubToken: 122er
      librariesIoToken: 121212sa
      s3BucketForAnalyses: deepshar-bayesian-core-data
      s3BucketForPackageAnalyses: deepshar-bayesian-core-package-data
    database: 
      dbName: coreapi
      host:     localhost
      initialDatabase: postgres
      password: coreapi
      port: "5432"
      username: coreapi
    npmInsights:
      bucket: "deepshar-cvae-insights"
    pypiInsights:
      bucket: "deepshar-hpf-pypi-insights"
    mavenInsights:
      bucket: "deepshar-hpf-maven-insights"
  pgbouncer:
    image: sharma1725/pgbouncer:latest
    name: bayesian-pgbouncer
    size: 1
  gremlin:
    image: quay.io/openshiftio/bayesian-gremlin:latest
    name: bayesian-gremlin-http
    dynamoDbEndpoint: "https://dynamodb.us-east-1.amazonaws.com"
    developerAnalyticsAuditReportS3: "deepshar-developer-analytics-audit-report"
    size: 1
    resources:
      limits:
        cpu: "1000m"
        memory: "1536Mi"
      requests:
        cpu: "500m"
        memory: "1536Mi"
  worker:
    name: bayesian-worker-api
    size: 1
    image: sharma1725/worker
    resources:
      limits:
        cpu: "1536m"
        memory: "500Mi"
      requests:
        cpu: "250m"
        memory: "500Mi"
  api-server: 
    image: quay.io/deepshar/aserver
    size: 1
    containerPort: 5000
    name: api-server
    port: 32000
  backbone:
    image: quay.io/deepshar/backbone
    size: 1
    containerPort: 5000
    name: backbone
    port: 32000
  snykSecrets:
    tokenEncryptionKey: token_key
    iss: iss
    token: token
