apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        service: f8a-license-analysis
    name: f8a-license-analysis
spec:
    replicas: 1
    selector:
        matchLabels:
            service: f8a-license-analysis
    template:
        metadata:
            labels:
                service: f8a-license-analysis
        spec:
            containers:
            -   command:
                    - /bin/entrypoint.sh
                env:
                -   name: DEPLOYMENT_PREFIX
                    valueFrom:
                        configMapKeyRef:
                            name: bayesian-config
                            key: deployment-prefix
                -   name: SERVICE_PORT
                    value: "6162"
                -   name: SERVICE_TIMEOUT
                    value: "900"
                -   name: DATA_DIR
                    value: "/"
                -   name: MAJORITY_THRESHOLD
                    value: "0.6"
                -   name: DISABLE_AUTHENTICATION
                    value: "0"
                -   name: FABRIC8_ANALYTICS_JWT_AUDIENCE
                    value: "fabric8-online-platform,openshiftio-public,https://prod-preview.openshift.io,https://openshift.io"
                -   name: OSIO_AUTH_URL
                    valueFrom:
                        configMapKeyRef:
                            name: bayesian-config
                            key: auth-url
                -   name: BAYESIAN_GREMLIN_HTTP_SERVICE_HOST
                    value: bayesian-gremlin-http
                -   name: BAYESIAN_GREMLIN_HTTP_SERVICE_PORT
                    value: "8182"
                -   name: SENTRY_DSN
                    valueFrom:
                        secretKeyRef:
                            name: worker
                            key: sentry_dsn
                name: f8a-license-analysis
                image: quay.io/openshiftio/fabric8-analytics-license-analysis
                ports:
                - containerPort: 6162
                livenessProbe:
                    httpGet:
                        path: /
                        port: 6162
                    initialDelaySeconds: 15
                    periodSeconds: 60
                    timeoutSeconds: 15
                readinessProbe:
                    httpGet:
                        path: /
                        port: 6162
                    initialDelaySeconds: 15
                    periodSeconds: 60
                    timeoutSeconds: 15
                resources:
                    requests:
                        cpu: "100m"
                        memory: "128Mi"
                    limits:
                        cpu: "250m"
                        memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
    labels:
        service: f8a-license-analysis
    name: f8a-license-analysis
spec:
    ports:
    -   port: 6162
        targetPort: 0
    selector:
        service: f8a-license-analysis
